### PR TITLE
Added version as an include file

### PR DESCRIPTION
**Pull request by procount**
Just a suggestion to ease future maintenance as the kernel advances.
Allows kernel version and release tag to be specified once and reused across scripts.
(I've not built with this change yet.)

### CODE REVIEW

**Comment by procount** [comment]
KERNEL was not a good choice for the variable name, because it is already used. Need to think of a better name instead.

**Comment by procount** [comment]
The build procedure seemed to work ok with this change. 
(Please check the version used and update accordingly if you decide to merge this. I think I'm a couple of days out now)
Now to have a play with ZFS! Should this work on both 32-bit and 64-bit kernels?

**Comment by andrum99** [comment]
May thanks for doing this - I had been meaning to do it myself to make things a bit easier but hadn't quite got round to it.

**Comment by andrum99** [comment]
> Should this work on both 32-bit and 64-bit kernels?

See the health warning in README.md about using ZFS on 32-bit kernels. There is apparently at least one tweak needed to the 32-bit kernel to make it work reliably - I've not investigated any further as I don't trust it on the 32-bit kernel, since development has been targetted at 64-bit platforms only for several years, from what I can gather.

**Comment by procount** [comment]
OK. I'm rebuilding it all again from a new installation, because I think the build failure last time caused it to break - it would ONLY work in the 32-bit /32-bit environment, and not in either of the 64/32 or 64/64 bit environments (missing libs & modules). Well, that was until it froze when I was copying from one dataset snapshot to another.

Yes, I understood it was really only for 64 bit-kernels. So will this build allow it to run in the 32bit Raspbian userland AND the 64-bit nspawn64 environment?

**Comment by procount** [comment]
Finally success!
I think my system was having trouble with build64_part2.sh because when I first rebooted into the 64/32 environment I still couldn't modprobe zfs. On next reboot, I ran depmod manually and now the modules are known and loadable.

Previously I created 2 datasets in the 32/32 world, snapshotted one and tried to send it to the other. It froze half way through. But I managed to import this zpool again and the send worked fine under 64/32 bit env. Time for some more playing. Thanks for the scripts.

**Comment by andrum99** [comment]
I've only tested mounting a zpool under the 32-bit kernel to check the modules had been built and were loading ok - I then reboot into the 64-bit kernel, run depmod -a and mount my zpools, and thats my NAS running normally. I don't touch the zfs commands in the 64-bit systemd-nspawn container, but they should work ok. I've not tried zfs send / receive at all.

**Comment by andrum99** [comment]
ZFS is known to be problematic on 32-bit linux kernels. It can apparently be made more stable by adding vmalloc=512M to /boot/cmdline.txt, but really you just have to run it on a 64-bit kernel.

**Comment by andrum99** [comment]
Just to clarify - 64-bit kernel with 32-bit userland is what I use and it works OK. I've not tried zfs send / receive though.

**Comment by procount** [comment]
Perhaps it would be useful to add the `depmod -a`  step to the readme as step 8.1, possibly followed by `modprobe zfs` (unless I missed something and this should have worked in build64_part2.sh)?

**Comment by andrum99** [comment]
> Perhaps it would be useful to add the `depmod -a` step to the readme as step 8.1, possibly followed by `modprobe zfs` (unless I missed something and this should have worked in build64_part2.sh)?

Yup - added.

**Pull request merged**
